name: Compile LaTeX Resume

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install TeX Live
      run: sudo apt-get update && sudo apt-get install -y texlive texlive-latex-extra

    - name: Compile Resume
      run: pdflatex -interaction=nonstopmode Resume.tex

    - name: Commit PDF to repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add Resume.pdf
        git commit -m "Update compiled Resume.pdf"
        git push